### PR TITLE
Reduced Docker image size

### PR DESCRIPTION
**Pull request by RoastVeg**
This MR changes the Docker image to use Alpine 3 instead of Ubuntu Bionic Beaver.
Additionally, it also does the following:

- Removes the build dependencies after nginx is installed
- Changes the RMTP version to one patched for newer versions of gcc
- Starts the image with ash (via sh) instead of bash
- Adds the nginx user and group specifically, using the de-facto standard uid/gid across docker

All told, this brings the image size down from 634MB to a little under 100MB (see #1). Further savings can likely be made by removing the dependency on gettext (which appears in the launch script to parse arguments).

### CODE REVIEW

**Comment by michaelkamprath** [comment]
So this doesn't work with the shell scrip I use to build the `nginx` config and launch the `nginx` process. Specifically, the `[[ -v MULTISTREAMING_KEY_TWITCH ]]` test I use in bash doesn't seem to work in sh. When I launch the container build with this PR, I get this error:

```
sh: MULTISTREAMING_KEY_FACEBOOK: unknown operand
sh: MULTISTREAMING_KEY_TWITCH: unknown operand
sh: MULTISTREAMING_KEY_YOUTUBE: unknown operand
```

Could you fix this?

**Comment by RoastVeg** [comment]
Do the above commits resolve the issue?

**Comment by michaelkamprath** [comment]
@RoastVeg this still doesn't work because you removed stunnel, which is absolutely needed to support Facebook live-streaming. I've made changes to make your pull request work. 

Can you make this PR editable by me so that I can push my changes into it? [See here for instructions](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).

**Comment by RoastVeg** [comment]
> @RoastVeg this still doesn't work because you removed stunnel, which is absolutely needed to support Facebook live-streaming. I've made changes to make your pull request work.
> 
> Can you make this PR editable by me so that I can push my changes into it? [See here for instructions](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork).

This PR is editable by maintainers. Stunnel is added via apk, is there a problem with the way Alpine installs it?

**Comment by michaelkamprath** [comment]
Oh wait, my bad, it is being aded. The issue is that the executable name changed from `stunnel4` to `stunnel`, and the version of stunnel being added (v5) needs to be set up slightly differently. That's why the Facebook restreaming breaks in this PR. I will push my changes that fixes that into this PR shortly.

**Comment by michaelkamprath** [comment]
@RoastVeg OK, I corrected the tunnel integration and verified it works. Please review my work before I merge this pull request. Thanks!

**Comment by michaelkamprath** [comment]
@RoastVeg I tested things out myself. I even have already used this build to run a livestream simulcast. So I wen ahead and merged it. Thanks!

Closes #1

**Comment by RoastVeg** [comment]
Can confirm that as of yesterday I also successfully simulcasted a live show using this. Many thanks for this project!

**Pull request merged**
