### PR TITLE
Add support for streaming audio only to Icecast servers.

### PR DESCRIPTION
**Pull request by jimdrie**
Note: Quality is currently hardcoded to 192 kbps MP3, can add environment variables for bitrate and format if this is preferred.

### CODE REVIEW

**Comment by michaelkamprath** [comment]
@jimdrie Thanks for this! Unfortunately, I'm about to merge something I have been working on that changes how everything is implemented, making this pull request needing to be reworked. Basically, I'm moving to JSON configuration and a better architecture to enable the proliferation of destination types. You can get a sneak peak in [the `json-config` branch](https://github.com/michaelkamprath/multi-service-rtmp-broadcaster/tree/json-config). I'll probably merge in the next day or so.  Can you rework your code in anticipation of the JSON configuration change, and then create a new pull request once I merge the JSON configuration changes?

**Comment by jimdrie** [comment]
No worries, will update it later I think. I made some changes too, removing the need to re-encode it and just taking the AAC stream (which is used the most in video streams) and pushing that to Icecast. This cuts down the CPU usage a lot. Will commit that soon and have a look when you merged the json-config branch.

**Comment by michaelkamprath** [comment]
@jimdrie I've updated master with my changes. You will see that this pull request can no longer be merged given the changes. I'd recommend deleting this pull request, rebase your fork, create you changes in the new paradigm, and then create a new pull request.

**Comment by jimdrie** [comment]
Will re-add functionality.

**Pull request closed without merging**
